### ISSUE TITLE
Update get_zillowData.py to print more data

### ISSUE THREAD

**Issue by josephwms** [josephwms/eco395m-project1-midterm#24]
Update get_zillowData.py to run the entire process through all acceptable Bed/Bath combinations (some of these might get cut by 20pg query limit so make sure to check output count in the 'Pre_data' file.

Use os and csv module to combine the outputs into a masterFile

Use os and cvs model to create a Count.txt file which returns all the count for each query by bedbath and an 'is cut' == True/False so the user knows which data is missing and which is not

**Comment by ZixuanXu0116** [comment]
Fix the problem by updating get_zillowData.py. Add sections to run the entire process through all popular Bed/Bath combinations. Also, add sections to combine several CSV files into one and filter and keep rows with no empty values in specific columns in the CSV file.
